spring.application.name=medibook-user-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/medibook_user
spring.datasource.username=postgres
spring.datasource.password=1234db

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=localhost:9092

jwt.secret=your-super-secret-key-at-least-32-characters-long
jwt.expiration=86400000
#spring.profiles.active=${APP_ENV:dev}


spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

# CRITICAL: Replace this with the exact package path to your event class in this project
spring.kafka.consumer.properties.spring.json.value.default.type=com.semicolon.medibookuserservice.event.events.UserRegisteredEvent


# Trust your base packages so Jackson is allowed to instantiate the class
spring.kafka.consumer.properties.spring.json.trusted.packages=com.semicolon.*

# Change the Swagger UI path from /swagger-ui/index.html to /docs
springdoc.swagger-ui.path=/docs

# Sort endpoints alphabetically by HTTP method in the UI
springdoc.swagger-ui.operationsSorter=alpha