spring.application.name=medibook-user-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/medibook_user
spring.datasource.username=postgres
spring.datasource.password=1234db

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=localhost:9092

jwt.secret=your-super-secret-key-at-least-32-characters-long


spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.semicolon.medibookuserservice.event.events.UserRegisteredEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.semicolon.*
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.operationsSorter=alpha