spring.application.name=medibook-user-service

server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/medibook_users}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Kuse@6051}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

jwt.secret=${JWT_SECRET:bXlzdXBlcnNlY3JldGtleWZvcmp3dHNpZ25pbmcxMjM0NTY=}

spring.profiles.active=${APP_ENV:dev}